/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package com.baidusoso.image;

import java.awt.AlphaComposite;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.Toolkit;
import java.awt.geom.AffineTransform;
import java.awt.geom.RoundRectangle2D;
import java.awt.image.AffineTransformOp;
import java.awt.image.BufferedImage;
import java.awt.image.CropImageFilter;
import java.awt.image.FilteredImageSource;
import java.awt.image.ImageFilter;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URL;

import javax.imageio.ImageIO;

import static com.baidusoso.image.Icon.Policy.CropAtCenter;
import static com.baidusoso.image.Icon.Policy.CropAtTop;

public class Icon {

    enum Policy {
        Scaled(0), CropAtTop(1), CropAtCenter(2), CropAtBottom(3);
        int value;

        private Policy(int val) {
            this.value = val;
        }

        public static Policy valueOf(int value) {
            switch (value) {
                case 1:
                    return CropAtTop;
                case 2:
                    return CropAtCenter;
                case 3:
                    return CropAtBottom;
                default:
                    return Scaled;
            }
        }
    }

    static class TransformParams {
        float mXScale, mYScale;
        int mCropAtX, mCropAtY;
    }

    static TransformParams getTransformParams(BufferedImage image, Policy policy, int targetSize) {
        if (image == null || policy == null) {
            throw new NullPointerException("Empty image or policy!!! ");
        }
        int w = image.getWidth();
        int h = image.getHeight();
        float xscale = (float) targetSize / w;
        float yscale = (float) targetSize / h;

        TransformParams params = new TransformParams();
        if (policy == Policy.Scaled) {
            params.mXScale = xscale;
            params.mYScale = yscale;
            params.mCropAtX = params.mCropAtY = 0;
        } else {
            params.mXScale = params.mYScale = Math.max(xscale, yscale);
            if (policy == CropAtTop) {
                params.mCropAtX = params.mCropAtY = 0;
            } else if (policy == CropAtCenter) {
                params.mCropAtX = xscale > yscale ? 0 : (int) (w * yscale - targetSize) / 2;
                params.mCropAtY = xscale < yscale ? 0 : (int) (h * xscale - targetSize) / 2;
            } else {
                params.mCropAtX = xscale > yscale ? 0 : (int) (w * yscale - targetSize);
                params.mCropAtY = xscale < yscale ? 0 : (int) (h * xscale - targetSize);
            }
        }
        return params;
    }

    static InputStream getImageInputStreamByUrl(String url) {
        URL imgUrl = null;
        try {
            imgUrl = new URL(url);
            HttpURLConnection conn = (HttpURLConnection) imgUrl.openConnection();
            conn.setDoInput(true);
            conn.connect();
            return conn.getInputStream();
        } catch (MalformedURLException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }
        return null;
    }

    static InputStream getImageInputStreamByFilePath(String filePath) {
        try {
            return new FileInputStream(filePath);
        } catch (IOException e) {
            e.printStackTrace();
        }
        return null;
    }

    static BufferedImage getImage(String uri) throws IOException {
        if (uri == null) {
            throw new NullPointerException("uri is null!!!");
        }
        InputStream inputStream = null;
        if (uri.startsWith("http://")) {
            inputStream = getImageInputStreamByUrl(uri);
        } else {
            inputStream = getImageInputStreamByFilePath(uri);
        }
        try {
            return ImageIO.read(inputStream);
        } finally {
            if (inputStream != null) {
                try {
                    inputStream.close();
                } catch (Throwable e) {
                }
            }
        }
    }

    static BufferedImage scaledImage(BufferedImage image, TransformParams params) {
        AffineTransform affineTransform = new AffineTransform();
        affineTransform.setToScale(params.mXScale, params.mYScale);
        AffineTransformOp affineTransformOp = new AffineTransformOp(
                affineTransform, null);
        BufferedImage outputImage = new BufferedImage((int) (image.getWidth() * params.mXScale),
                (int) (image.getHeight() * params.mYScale), BufferedImage.TYPE_INT_ARGB);
        affineTransformOp.filter(image, outputImage);
        return outputImage;
    }

    static BufferedImage cropImage(BufferedImage image, TransformParams params, int targetSize) {
        ImageFilter cropFilter = new CropImageFilter(params.mCropAtX, params.mCropAtY, targetSize, targetSize);
        Image img = Toolkit.getDefaultToolkit().createImage(
                new FilteredImageSource(image.getSource(), cropFilter));
        BufferedImage outputImage = new BufferedImage(targetSize, targetSize,
                BufferedImage.TYPE_INT_ARGB);

        Graphics g = outputImage.getGraphics();
        g.drawImage(img, 0, 0, null);
        g.dispose();
        return outputImage;
    }

    static BufferedImage roundImage(BufferedImage image, int targetSize, int cornerRadius) {
        BufferedImage outputImage = new BufferedImage(targetSize, targetSize, BufferedImage.TYPE_INT_ARGB);
        Graphics2D g2 = outputImage.createGraphics();
        g2.setComposite(AlphaComposite.Src);
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(Color.WHITE);
        g2.fill(new RoundRectangle2D.Float(0, 0, targetSize, targetSize, cornerRadius, cornerRadius));
        g2.setComposite(AlphaComposite.SrcAtop);
        g2.drawImage(image, 0, 0, null);
        g2.dispose();
        return outputImage;
    }


    static void normalRoundImage(String imgUrl, String destFileString, int targetSize, int cornerRadius) throws Exception {
        InputStream inputStream = getImageInputStreamByUrl(imgUrl);
        if (inputStream != null) {
            try {
                BufferedImage image = ImageIO.read(inputStream);
                //scale
                int w = image.getWidth();
                int h = image.getHeight();
                float xscale = (float) targetSize / w;
                float yscale = (float) targetSize / h;
                float scale = Math.max(xscale, yscale);
                AffineTransform affineTransform = new AffineTransform();
                affineTransform.setToScale(scale, scale);
                AffineTransformOp affineTransformOp = new AffineTransformOp(
                        affineTransform, null);
                BufferedImage outputImage = new BufferedImage((int) (w * scale),
                        (int) (h * scale), BufferedImage.TYPE_INT_ARGB);
                affineTransformOp.filter(image, outputImage);

                //crop
                int x = xscale > yscale ? 0 : (int) (w * yscale - targetSize) / 2;
                int y = xscale < yscale ? 0 : (int) (h * xscale - targetSize) / 2;
                ImageFilter cropFilter = new CropImageFilter(x, y, targetSize, targetSize);
                Image img = Toolkit.getDefaultToolkit().createImage(
                        new FilteredImageSource(outputImage.getSource(), cropFilter));
                BufferedImage tag = new BufferedImage(targetSize, targetSize,
                        BufferedImage.TYPE_INT_ARGB);

                Graphics g = tag.getGraphics();
                g.drawImage(img, 0, 0, null);
                g.dispose();

                //roundrect
                BufferedImage output = new BufferedImage(targetSize, targetSize, BufferedImage.TYPE_INT_ARGB);
                Graphics2D g2 = output.createGraphics();
                g2.setComposite(AlphaComposite.Src);
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                g2.setColor(Color.WHITE);
                g2.fill(new RoundRectangle2D.Float(0, 0, targetSize, targetSize, cornerRadius, cornerRadius));
                g2.setComposite(AlphaComposite.SrcAtop);
                //xscale>yscale?0.0F:(w*yscale-targetSize)/2, xscale<yscale?0.0F:(h*xscale-targetSize)/2
                g2.drawImage(tag, 0, 0, null);
                g2.dispose();

                ImageIO.write(output, "png", new File(destFileString));
            } finally {
                if (inputStream != null) {
                    try {
                        inputStream.close();
                    } catch (Throwable e) {
                    }
                }
            }
        } else {
            System.out.println("Fail to get Image data!!!");
        }
    }

    static void showUsage() {
        System.out.println("java -jar RoundIcon.jar image [output path] [output image size] [cornerRadius] [policy:0,1,2,3]");
    }

    public static void main(String[] args) throws Exception {
        if (args == null || args.length == 0) {
            showUsage();
            return;
        }
        String uri = args[0];
        String targetPath = "icon.png";
        if (args.length >= 2) {
            targetPath = args[1];
        }
        int targetSize = 96;
        if (args.length >= 3) {
            targetSize = Integer.parseInt(args[2]);
        }
        int cornerRadius = 20;
        if (args.length >= 4) {
            cornerRadius = Integer.parseInt(args[3]);
        }
        Policy policy = Policy.Scaled;
        if (args.length >= 5) {
            policy = Policy.valueOf(Integer.parseInt(args[4]));
        }
        BufferedImage image = getImage(uri);
        if (image == null) {
            System.out.println("Fail to get Image data!!!");
            return;
        }
        TransformParams params = getTransformParams(image, policy, targetSize);
        BufferedImage outputImage = scaledImage(image, params);
        outputImage = cropImage(outputImage, params, targetSize);
        outputImage = roundImage(outputImage, targetSize, cornerRadius);
        ImageIO.write(outputImage, "png", new File(targetPath));
        System.out.println("Done");
    }
}
