/*
 * This Java source file was generated by the Gradle 'init' task.
 */
 
package com.baidusoso.image;

import java.awt.AWTException;
import java.awt.AlphaComposite;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.Toolkit;
import java.awt.geom.RoundRectangle2D.Float;
import java.awt.image.BufferedImage;
import java.awt.image.MemoryImageSource;
import java.awt.image.PixelGrabber;
import java.io.File;
import java.io.IOException;
import java.io.PrintStream;
import javax.imageio.ImageIO;

public class Icon {

		public static void normalRoundImage(String argsFileString, String destFileString)
    throws Exception
  {
    normalRoundImage(argsFileString, destFileString, 15);
  }

  public static void normalRoundImage(String argsFileString, String destFileString, int cornerRadius) throws Exception
  {
    BufferedImage image = ImageIO.read(new File(argsFileString));
    int w = image.getWidth();
    int h = image.getHeight();
    BufferedImage output = new BufferedImage(w, h, 
      2);

    Graphics2D g2 = output.createGraphics();

    g2.setComposite(AlphaComposite.Src);
    g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, 
      RenderingHints.VALUE_ANTIALIAS_ON);
    g2.setColor(Color.WHITE);
    g2.fill(
      new RoundRectangle2D.Float(0.0F, 0.0F, w, h, cornerRadius, 
      cornerRadius));

    g2.setComposite(AlphaComposite.SrcAtop);
    g2.drawImage(image, 0, 0, null);

    g2.dispose();
    ImageIO.write(output, "png", new File(destFileString));
  }
    public static void main(String[] args) {
        normalRoundImage("d:/icon/920s.jpg","icon.png",20);
    }
}
